In [11]:
# !pip install datasets

In [12]:
from datasets import load_dataset

In [13]:
dataset = load_dataset("tankado/Dutch_Census")

In [14]:
dataset["train"]

Dataset({
    features: ['age', 'household_position', 'household_size', 'prev_residence_place', 'citizenship', 'country_birth', 'edu_level', 'economic_status', 'cur_eco_activity', 'Marital_status', 'sex_binary', 'occupation_binary'],
    num_rows: 60420
})

In [15]:
from Utils.tabular_data_loader import dataset_to_numpy

In [16]:
import pandas as pd

df = pd.DataFrame(dataset["train"])

In [17]:
dutch_df_feature_columns = [
    "age",
    "household_position",
    "household_size",
    "prev_residence_place",
    "citizenship",
    "country_birth",
    "edu_level",
    "economic_status",
    "cur_eco_activity",
    "Marital_status",
    "sex_binary",
]
metadata_dutch = {
    "name": "Dutch census",
    "code": ["DU1"],
    "protected_atts": ["sex_binary"],
    "protected_att_values": [0],
    "protected_att_descriptions": ["Gender = Female"],
    "target_variable": "occupation_binary",
}

In [18]:
dataset_to_numpy(
    _df=df,
    _feature_cols=dutch_df_feature_columns,
    _metadata=metadata_dutch,
)

['age', 'household_position', 'household_size', 'prev_residence_place', 'citizenship', 'country_birth', 'edu_level', 'economic_status', 'cur_eco_activity', 'Marital_status', 'sex_binary']
Index(['age', 'household_position', 'household_size', 'prev_residence_place',
       'citizenship', 'country_birth', 'edu_level', 'economic_status',
       'cur_eco_activity', 'Marital_status', 'sex_binary',
       'occupation_binary'],
      dtype='object')
Using ['sex_binary'] as sensitive feature(s).


(array([[0.18181818, 0.19090909, 0.06666667, ..., 0.        , 0.85714286,
         0.        ],
        [0.54545455, 0.10909091, 0.13333333, ..., 0.        , 0.39285714,
         0.33333333],
        [0.36363636, 0.10909091, 0.13333333, ..., 0.        , 0.39285714,
         0.33333333],
        ...,
        [0.63636364, 0.1       , 0.06666667, ..., 0.        , 0.85714286,
         0.33333333],
        [0.27272727, 0.19090909, 0.06666667, ..., 0.        , 0.92857143,
         0.        ],
        [0.72727273, 0.1       , 0.06666667, ..., 0.        , 0.92857143,
         0.33333333]]),
 array([[0, 1],
        [1, 0],
        [0, 1],
        ...,
        [0, 1],
        [1, 0],
        [0, 1]], dtype=uint8),
 array([0, 1, 0, ..., 0, 0, 0]))