In [1]:
import numpy as np

In [21]:
shap_1 = [0.5, 0.3, 0.8]
shap_2 = [0.2, 0.6, 0.4]
weights_f1 = [0.9, 0.7]
weights_faith = [0.1, 0]

avg = np.average([shap_1, shap_2], axis=0)
weighted_avg_f1 = np.average([shap_1, shap_2], weights=weights_f1, axis=0)
weighted_avg_faith = np.average([shap_1, shap_2], weights=weights_faith, axis=0)

print(avg)
print(weighted_avg_f1)
print(weighted_avg_faith)

[0.35 0.45 0.6 ]
[0.36875 0.43125 0.625  ]
[0.5 0.3 0.8]


In [16]:
shap_1 = [0.5, 0.3, 0.8]
shap_2 = [0.2, 0.6, 0.4]
weights_f1 = [0.9, 0.7]
weights_faith = [0.2, -0.2]

avg = np.average([shap_1, shap_2], axis=0)
weighted_avg_f1 = np.average([shap_1, shap_2], weights=weights_f1, axis=0)
weighted_avg_faith = np.average([shap_1, shap_2], weights=weights_faith, axis=0)

print(avg)
print(weighted_avg_f1)
print(weighted_avg_faith)

ZeroDivisionError: Weights sum to zero, can't be normalized

In [20]:
shap_1 = [0.5, 0.3, 0.8]
shap_2 = [0.2, 0.6, 0.4]
weights_f1 = [0.9, 0.7]
weights_faith = [0.2, -0.19]


avg = np.average([shap_1, shap_2], axis=0)
weighted_avg_f1 = np.average([shap_1, shap_2], weights=weights_f1, axis=0)
weighted_avg_faith = np.average([shap_1, shap_2], weights=weights_faith, axis=0)

print(avg)
print(weighted_avg_f1)
print(weighted_avg_faith)

[0.35 0.45 0.6 ]
[0.36875 0.43125 0.625  ]
[ 6.2 -5.4  8.4]


In [22]:
shap_1 = [0.5, 0.3, 0.8]
shap_2 = [0.2, 0.6, 0.4]
weights_f1 = [0.9, 0.7]
weights_faith = [0.6, 0.1]


avg = np.average([shap_1, shap_2], axis=0)
weighted_avg_f1 = np.average([shap_1, shap_2], weights=weights_f1, axis=0)
weighted_avg_faith = np.average([shap_1, shap_2], weights=weights_faith, axis=0)

print(avg)
print(weighted_avg_f1)
print(weighted_avg_faith)

[0.35 0.45 0.6 ]
[0.36875 0.43125 0.625  ]
[0.45714286 0.34285714 0.74285714]


In [ ]:
import os
import dill

if os.path.exists("/home/lcorbucci/data/celeba/celeba-10-batches-py/federated_4/sum_counters.pkl"):
    with open(
        "/home/lcorbucci/data/celeba/celeba-10-batches-py/federated_4/sum_counters.pkl",
        "rb",
    ) as file:
        sum_counters = dill.load(file)

sum_counters

NameError: name 'sum_counters' is not defined